name: 👷 CI/CD (Node.JS)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "/app/"
      - "/components/"
      - "/hooks/"
      - "/lib/"
  push:
    branches: [main]
    paths:
      - "/app/"
      - "/components/"
      - "/hooks/"
      - "/lib/"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build
